# Generated by Django 3.1.3 on 2020-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=300)),
                ('product_desc', models.CharField(max_length=300)),
                ('product_model', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
