# Generated by Django 3.1.3 on 2020-11-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20201126_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
