# Generated by Django 3.1.3 on 2020-11-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_product_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='watch3', max_length=500, upload_to='pictures'),
        ),
    ]
