# Generated by Django 3.1.3 on 2020-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_auto_20201130_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='watch3.jpg', max_length=500, upload_to='pictures'),
        ),
    ]
