# Generated by Django 3.1.3 on 2020-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_auto_20201130_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', max_length=500, upload_to=''),
        ),
    ]
