# Generated by Django 3.1.3 on 2020-12-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
