# Generated by Django 3.1.3 on 2020-12-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0015_auto_20201228_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
    ]
